
modLoader="javafml"
loaderVersion = "[47,)"
license = "GNU General Public License"

[[mods]]
modId="gobtweaks"
version="0.7.2"
displayName="Global Tweaks"
authors="gobies"
description='''Various tweaks for many different mods and vanilla features'''

[[dependencies.gobtweaks]]
modId="forge"
mandatory= true
versionRange = "[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.gobtweaks]]
modId="minecraft"
mandatory= true
versionRange = "[1.20.1]"
ordering="NONE"
side="BOTH"

[modproperties.gobtweaks]
configuredBackground="minecraft:textures/block/stone_bricks.png"
catalogueImageIcon = "icon.png"

